name: Build SGTK and Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python .github/scripts/install_build_dependencies.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run SGTK Build Script
        run: |
          python sgtk/_build_sgtk.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Upload build artifact
#        uses: softprops/action-gh-release@v2
#        with:
#          files: _build/*.zip
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}